
CREATE  TABLE IF NOT EXISTS `androidglass_DEVICE` (
  `androidglass_DEVICE_ID` VARCHAR(45) NOT NULL ,
  `DEVICE_NAME` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`androidglass_DEVICE_ID`) )
ENGINE = InnoDB;




